-- SQL Schema definition for the Users table
-- Target Database: Microsoft SQL Server / Azure SQL Database

CREATE TABLE Users (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    fullName NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) NOT NULL UNIQUE,
    phone NVARCHAR(50) NOT NULL,
    password NVARCHAR(255) NOT NULL,
    role NVARCHAR(50) NOT NULL CHECK (role IN ('Admin', 'Doctor', 'Patient')),
    preferredLanguage NVARCHAR(50) DEFAULT 'en',
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE Doctors (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    userId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    specialization NVARCHAR(255) NOT NULL,
    qualification NVARCHAR(255) NOT NULL,
    experienceYears INT NOT NULL,
    hospitalName NVARCHAR(255) NOT NULL,
    consultationFee DECIMAL(10, 2) NOT NULL,
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT FK_Doctors_Users FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE DoctorAvailabilities (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    doctorId UNIQUEIDENTIFIER NOT NULL,
    dayOfWeek NVARCHAR(50) NOT NULL CHECK (dayOfWeek IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    slotDuration INT NOT NULL,
    isActive BIT NOT NULL DEFAULT 1,
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT FK_DoctorAvailabilities_Doctors FOREIGN KEY (doctorId) REFERENCES Doctors(id) ON DELETE CASCADE
);

CREATE TABLE Appointments (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    patientId UNIQUEIDENTIFIER NOT NULL,
    doctorId UNIQUEIDENTIFIER NOT NULL,
    appointmentDate DATE NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    status NVARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Completed', 'Cancelled')),
    notes NVARCHAR(MAX),
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT FK_Appointments_Users FOREIGN KEY (patientId) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT FK_Appointments_Doctors FOREIGN KEY (doctorId) REFERENCES Doctors(id) ON DELETE NO ACTION
);

CREATE TABLE MedicalRecords (
    recordId UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    patientId UNIQUEIDENTIFIER NOT NULL,
    blobUrl NVARCHAR(2048) NOT NULL,
    blobName NVARCHAR(512) NOT NULL,
    documentType NVARCHAR(100) NOT NULL,
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT FK_MedicalRecords_Users FOREIGN KEY (patientId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Notifications (
    id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    userId UNIQUEIDENTIFIER NOT NULL,
    type NVARCHAR(50) NOT NULL CHECK (type IN ('Email', 'SMS')),
    recipient NVARCHAR(255) NOT NULL,
    title NVARCHAR(255) NOT NULL,
    message NVARCHAR(MAX) NOT NULL,
    status NVARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Sent', 'Failed')),
    sentAt DATETIMEOFFSET NULL,
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT FK_Notifications_Users FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
